
DROP TABLE IF EXISTS sizes;
DROP TABLE IF EXISTS colors;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS operation_type;
DROP TABLE IF EXISTS inventory_log;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS images_sizes;
DROP TABLE IF EXISTS images_categories;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS subcategories;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;